### ISSUE TITLE
Leveled cannot recover after a disk-full error.

### ISSUE THREAD

**Issue by kape1395** [martinsumner/leveled#262] opened 2019-02-19 07:14 UTC
I got situation, where a disk got full. After releasing some space in the disk, the leveled db still fails to recover. There are the errors:

````
2019-02-18 14:27:41.510 [error] <0.3866.0>      CRASH REPORT Process <0.3866.0> with 11 neighbours exited with reason: no match of right hand value <<>> in leveled_pmanifest:open_manifestfile/2 line 851 in gen_server:init_it/6 line 352
2019-02-18 14:27:41.512 [error] <0.3818.0>      CRASH REPORT Process <0.3818.0> with 0 neighbours exited with reason: no match of right hand value {error,{{badmatch,<<>>},[{leveled_pmanifest,open_manifestfile,2,[{file,"src/leveled_pmanifest.erl"},{line,851}]},{leveled_penciller,start_from_file,1,[{file,"src/leveled_penciller.erl"},{line,1135}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}} in mnesia_leveled:open_leveled_/2 line 987 in gen_server:init_it/6 line 352
2019-02-18 14:27:41.514 [info]  <0.1323.0>      mnesia_system_event:mnesia_info: Receiver failed on 'eproc$msg' from 'litgrid-statera@vlnlgtv-str002.litcorp.litgrid.eu':
Reason: {{{case_clause,{error,{{{badmatch,{error,{{badmatch,<<>>},[{leveled_pmanifest,open_manifestfile,2,[{file,"src/leveled_pmanifest.erl"},{line,851}]},{leveled_penciller,start_from_file,1,[{file,"src/leveled_penciller.erl"},{line,1135}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]}}},[{mnesia_leveled,open_leveled_,2,[{file,"src/mnesia_leveled.erl"},{line,987}]},{mnesia_leveled,do_load_table,2,[{file,"src/mnesia_leveled.erl"},{line,873}]},{mnesia_leveled,init,1,[{file,"src/mnesia_leveled.erl"},{line,858}]},{gen_server,init_it,6,[{file,"gen_server.erl"},{line,328}]},{proc_lib,init_p_do_apply,3,[{file,"proc_lib.erl"},{line,247}]}]},{child,undefined,'eproc$msg',{mnesia_leveled,start_proc,[leveled_copies,'eproc$msg',set,[{log_level,error}]]},transient,120000,worker,[mnesia_leveled]}}}},[{mnesia_leveled,load_table_,4,[{file,"src/mnesia_leveled.erl"},{line,409}]},{mnesia_loader,ext_init_table,6,[{file,"mnesia_loader.erl"},{line,482}]},{mnesia_loader,do_init_table,8,[{file,"mnesia_loader.erl"},{line,372}]},{mnesia_loader,spawned_receiver,8,[{file,"mnesia_loader.erl"},{line,342}]}]},[{mnesia_loader,wait_on_load_complete,1,[{file,"mnesia_loader.erl"},{line,358}]},{mnesia_tm,apply_fun,3,[{file,"mnesia_tm.erl"},{line,836}]},{mnesia_tm,execute_transaction,5,[{file,"mnesia_tm.erl"},{line,811}]},{mnesia_loader,init_receiver,5,[{file,"mnesia_loader.erl"},{line,284}]},{mnesia_loader,do_get_network_copy,5,[{file,"mnesia_loader.erl"},{line,220}]},{mnesia_controller,'-load_table_fun/1-fun-3-',5,[{file,"mnesia_controller.erl"},{line,2180}]},{mnesia_controller,'-load_and_reply/2-fun-0-',2,[{file,"mnesia_controller.erl"},{line,2138}]}]}
````

**Comment by kape1395** [comment] 2019-02-19 07:45
I have managed to recover the database by deleting an empty *.man file, although I have not checked the data for integrity yet.

**Comment by martinsumner** [comment] 2019-02-19 08:49
If you remove the ledger altogether, then leveled should recover from the Journal.  There are tests of this in https://github.com/martinsumner/leveled/blob/master/test/end_to_end/recovery_SUITE.erl.

The backup method only backs up the journal, as this can happen safely.  Note though, this does not work in head_only mode.

**Comment by kape1395** [comment] 2019-02-19 09:07
Can that be done automatically, if the ledger is corrupted?

**Comment by martinsumner** [comment] 2019-02-19 09:19
I've not considered automating this as of yet.  Perhaps it is better to give an admin a chance to investigate the cause of the corruption rather than wiping the evidence by automating the recovery?

**Comment by martinsumner** [comment] 2021-10-05 08:51
Closing this, as there exists a workaround (i.e. rebuild the ledger) - and the risk of automation may outweigh the benefits.

**Closed by martinsumner** 2021-10-05 08:51 UTC
